<?php
namespace DigitalStars\SimpleVK;
$path_dir =  __DIR__.'/src';
require_once($path_dir.'/FileUploader.php');
require_once($path_dir.'/BaseConstructor.php');
require_once($path_dir.'/Carousel.php');
require_once($path_dir.'/Message.php');
require_once($path_dir.'/Post.php');
require_once($path_dir.'/ErrorHandler.php');
require_once($path_dir.'/SimpleVK.php');
require_once($path_dir.'/SimpleVkException.php');
require_once($path_dir.'/Auth.php');
require_once($path_dir.'/LongPoll.php');
require_once($path_dir.'/Streaming.php');
//require_once($path_dir.'/Coin.php');
//require_once($path_dir.'/Execute.php');
require_once($path_dir.'/SiteAuth.php');
require_once($path_dir.'/Bot.php');
require_once($path_dir.'/Store.php');
require_once($path_dir.'/Diagnostics.php');